package com.structis.vip.shared.exception;

public enum ExceptionType {		
	UNKNOWN,
	DEL_INSERT_DUPLICATE,
	DEL_UPDATE_DUPLICATE, DEL_SAME_DELEGANT_DELEGANTAIRE, DEL_START_AFTER_END_DATE, DEL_TYPE_NOT_SET, DEL_TEMP_OF_TEMP, DEL_DELETE_DELEGATION_IS_PARENT, 
	DEL_UNIQUE_DELEGANT, DELEGATION_MODEL_EXIST, DELEGATION_MODEL_USED_IN_RULES,
	DELEGATION_TYPE_SAME_NAME,
	PERIMETRE_SYNC_FAILED, PERIMETRE_HAS_CHILDREN, PERIMETRE_USED_IN_DELEGATION, PERIMETRE_USED_IN_COLLABORATEUR, PERIMETRE_USED_IN_ROLE, PERIMETRE_USED_IN_USER,
	USER_DUPLICATED, USER_NOT_AUTHORIZED, USER_PASSWORD_INCORRECT,
	COLLABORATEUR_USED_IN_DELEGATION,
	ENTITE_JUR_DELETE_EXIST_IN_PERIMETRE, ENTITE_JUR_DELETE_DEFAULT, ENTITE_JUR_DELETE_EXIST_IN_DELEGATION,
	LANGUAGE_DELETE_EXIST_IN_PERIMETRE, LANGUAGE_DELETE_EXIST_IN_DELEGATION_MODEL, LANGUAGE_DELETE_EXIST_IN_DOCUMENT_MODEL, LANGUAGE_DELETE_EXIST_IN_FIELD, LANGUAGE_DELETE_DEFAULT, LANGUAGE_DELETE_EXIST_IN_ENTITE,
	CHANTIER_TYPE_DELETE_EIXST,
	NATURE_DELETE_EIXIST_IN_DELEGATION, NATURE_DELETE_EIXIST_IN_DELEGATION_MODEL,
	DOCUMENT_DELETE_EXIST_IN_DELEGATION_MODEL, DOCUMENT_DELETE_EXIST_IN_DELEGATION, DOCUMENT_INSERT_DUPLICATE_NAME, PERIMETRE_TYPE_DELETE_EIXST;
}