/*
 * Generated by Celerio, a Jaxio tool. http://www.jaxio.com/
 */
package com.structis.vip.server.dao.hibernate;

import org.apache.commons.lang.Validate;
import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Disjunction;
import org.hibernate.criterion.Example;
import org.hibernate.criterion.Junction;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.hibernate.type.Type;

import com.structis.vip.server.dao.support.DateRange;
import com.structis.vip.server.dao.support.SearchMode;
import com.structis.vip.server.dao.support.SearchTemplate;

/**
 * Provide utility methods to create MatchMode, Example or Criteria.
 */
public abstract class HibernateUtil {

    public static final Example.PropertySelector NOT_NULL_OR_EMPTY = new HibernateUtil.NotNullOrEmptyPropertySelector();

    static final class NotNullOrEmptyPropertySelector implements Example.PropertySelector {

        private static final long serialVersionUID = 1L;

        @Override
        public boolean include(Object object, String propertyName, Type type) {
            if (object != null) {
                if ((object instanceof String) && "".equals(object)) {
                    return false;
                }

                return true;
            }

            return false;
        }
    }

    /**
     * Convert a local SearchMode to an Hibernate MatchMode.
     * 
     * @return the corresponding hibernate match mode
     */
    public static MatchMode convertSearchModeToMatchMode(SearchMode searchMode) {
        switch (searchMode) {
        case ANYWHERE:
            return MatchMode.ANYWHERE;
        case STARTING_LIKE:
            return MatchMode.START;
        case ENDING_LIKE:
            return MatchMode.END;
        case LIKE: // fall through
        case EQUALS: // fall through
        default:
            return MatchMode.EXACT;
        }
    }

    /**
     * Create an example from the passed object and configure it using the passed searchTemplate.
     * 
     * @return the configured example.
     */
    public static Example constructExample(Object object, SearchTemplate searchTemplate) {
        Validate.notNull(object, "The passed sample cannot be null");

        Example example = Example.create(object);
        // do not use example.excludeZeroes()
        // we prefer to use our own property selector to exclude empty string since oracle treat them as null!
        // also since our number properties are object and not primary types, it is better to keep them,
        // as 0 value are intentional
        example.setPropertySelector(NOT_NULL_OR_EMPTY);

        if (searchTemplate != null) {
            MatchMode matchMode = convertSearchModeToMatchMode(searchTemplate.getSearchMode());

            if (searchTemplate.isCaseInsensitive()) {
                // lower case comparison is done only when 'like' is activated. Is it an hibernate bug ?
                example.enableLike(matchMode);
                example.ignoreCase();
            } else if (searchTemplate.getSearchMode() != SearchMode.EQUALS) {
                example.enableLike(matchMode);
            }
        }

        return example;
    }

    /**
     * Construct a OR criterion.
     * 
     * @param stringColumns
     * @param searchTemplate
     * @return the criterion
     */
    public static Criterion constructPattern(String[] stringColumns, SearchTemplate searchTemplate) {
        if (stringColumns.length == 0 || searchTemplate == null || !searchTemplate.hasSearchPattern()) {
            return null;
        }

        MatchMode matchMode = convertSearchModeToMatchMode(searchTemplate.getSearchMode());
        Disjunction disjunction = Restrictions.disjunction();

        for (String stringColumn : stringColumns) {
            Criterion criterion = constructPatternCriterion(stringColumn, searchTemplate.getSearchPattern(), matchMode,
                    searchTemplate.isCaseSensitive());
            disjunction.add(criterion);
        }

        return disjunction;
    }

    public static Criterion constructDate(SearchTemplate searchTemplate) {
        if (searchTemplate == null || !searchTemplate.hasDatePattern()) {
            return null;
        }
        Junction junction = Restrictions.conjunction();

        for (DateRange dateRange : searchTemplate.getDateRanges()) {
            if (dateRange != null && dateRange.isSet()) {
                Criterion criterion = constructDateCriterion(dateRange);
                if (criterion != null) {
                    junction.add(criterion);
                }
            }
        }

        return junction;
    }

    public static Criterion constructDateCriterion(DateRange dateRange) {
        Criterion rangeCriterion = null;

        if (dateRange.isBetween()) {
            rangeCriterion = Restrictions.between(dateRange.getField(), dateRange.getFrom(), dateRange.getTo());
        } else if (dateRange.isFromSet()) {
            rangeCriterion = Restrictions.ge(dateRange.getField(), dateRange.getFrom());
        } else if (dateRange.isToSet()) {
            rangeCriterion = Restrictions.le(dateRange.getField(), dateRange.getTo());
        }

        if (rangeCriterion != null) {
            if (!dateRange.isIncludeNullSet() || dateRange.getIncludeNull() == Boolean.FALSE) {
                return rangeCriterion;
            } else {
                return Restrictions.or(rangeCriterion, Restrictions.isNull(dateRange.getField()));
            }
        }

        if (dateRange.getIncludeNull() == Boolean.TRUE) {
            return Restrictions.isNull(dateRange.getField());
        }

        if (dateRange.getIncludeNull() == Boolean.FALSE) {
            return Restrictions.isNotNull(dateRange.getField());
        }

        return null;
    }

    public static Criterion constructPatternCriterion(String columnName, String columnValue, SearchTemplate searchTemplate) {
        return constructPatternCriterion(columnName, columnValue, convertSearchModeToMatchMode(searchTemplate.getSearchMode()),
                searchTemplate.isCaseSensitive());
    }

    public static Criterion constructPatternCriterion(String columnName, String columnValue, MatchMode matchMode, boolean isCaseSensitive) {
        if (matchMode == MatchMode.EXACT) {
            return Restrictions.eq(columnName, columnValue);
        } else {
            if (isCaseSensitive) {
                return Restrictions.like(columnName, columnValue, matchMode);
            } else {
                return Restrictions.ilike(columnName, columnValue, matchMode);
            }
        }
    }

    /**
     * Helper method to apply on the passed Criteria the pagination and order by parameters found in the passed SearchTemplate.
     * 
     * @return the same hibernate criteria with first, max results and order by properties set.
     */
    public static Criteria applyPaginationAndOrderOnCriteria(Criteria criteria, SearchTemplate searchTemplate) {
        if (searchTemplate == null) {
            return criteria;
        }

        // set pagination if needed
        criteria.setFirstResult(searchTemplate.getFirstResult());
        criteria.setMaxResults(searchTemplate.getMaxResults());

        // set order criteria if available
        if (searchTemplate.hasOrderBy()) {
            if (searchTemplate.isOrderDesc()) {
                criteria.addOrder(Order.desc(searchTemplate.getOrderBy()));
            } else {
                criteria.addOrder(Order.asc(searchTemplate.getOrderBy()));
            }
        }
        return criteria;
    }
}
