--Update Ref_Type_Mch_AV table

IF NOT EXISTS( 
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'Ref_Type_Mch_AV' 
	AND COLUMN_NAME = 'ORDRE')
begin
	ALTER TABLE Ref_Type_Mch_AV ADD ORDRE INTEGER;
	
end
GO
UPDATE Ref_Type_Mch_AV SET ORDRE=1 WHERE UPPER(LIBELLE)='MCH';
UPDATE Ref_Type_Mch_AV SET ORDRE=2 WHERE UPPER(LIBELLE)='MCH1';
UPDATE Ref_Type_Mch_AV SET ORDRE=3 WHERE UPPER(LIBELLE)='MCH2';
UPDATE Ref_Type_Mch_AV SET ORDRE=4 WHERE UPPER(LIBELLE)='MCH3';
UPDATE Ref_Type_Mch_AV SET ORDRE=5 WHERE UPPER(LIBELLE)='MCH4';
UPDATE Ref_Type_Mch_AV SET ORDRE=6 WHERE UPPER(LIBELLE)='MCH5';
UPDATE Ref_Type_Mch_AV SET ORDRE=7 WHERE UPPER(LIBELLE)='AV1';
UPDATE Ref_Type_Mch_AV SET ORDRE=8 WHERE UPPER(LIBELLE)='AV2';
UPDATE Ref_Type_Mch_AV SET ORDRE=9 WHERE UPPER(LIBELLE)='AV3';
UPDATE Ref_Type_Mch_AV SET ORDRE=10 WHERE UPPER(LIBELLE)='AV4';
UPDATE Ref_Type_Mch_AV SET ORDRE=11 WHERE UPPER(LIBELLE)='AV5';
UPDATE Ref_Type_Mch_AV SET ORDRE=12 WHERE UPPER(LIBELLE)='AV6';
UPDATE Ref_Type_Mch_AV SET ORDRE=13 WHERE UPPER(LIBELLE)='AV7';
UPDATE Ref_Type_Mch_AV SET ORDRE=14 WHERE UPPER(LIBELLE)='AV8';
UPDATE Ref_Type_Mch_AV SET ORDRE=15 WHERE UPPER(LIBELLE)='AV9';
UPDATE Ref_Type_Mch_AV SET ORDRE=16 WHERE UPPER(LIBELLE)='AV10';
UPDATE Ref_Type_Mch_AV SET ORDRE=17 WHERE UPPER(LIBELLE)='RAT';

--Update Ref_Transfert_PP table
IF NOT EXISTS( 
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'Ref_Transfert_PP' 
	AND COLUMN_NAME = 'ORDRE')
begin
	ALTER TABLE Ref_Transfert_PP ADD ORDRE INTEGER;
end
GO
Update 
UPDATE Ref_Transfert_PP SET ORDRE=1 WHERE UPPER(LIBELLE)='MOD';
UPDATE Ref_Transfert_PP SET ORDRE=2 WHERE UPPER(LIBELLE)='HA';
UPDATE Ref_Transfert_PP SET ORDRE=3 WHERE UPPER(LIBELLE)='TS';
UPDATE Ref_Transfert_PP SET ORDRE=4 WHERE UPPER(LIBELLE)='Béton';
UPDATE Ref_Transfert_PP SET ORDRE=5 WHERE UPPER(LIBELLE)='Préfa';
UPDATE Ref_Transfert_PP SET ORDRE=6 WHERE UPPER(LIBELLE)='Autre MTX';
UPDATE Ref_Transfert_PP SET ORDRE=7 WHERE UPPER(LIBELLE)='Maîtrise';
UPDATE Ref_Transfert_PP SET ORDRE=8 WHERE UPPER(LIBELLE)='Encadrement';
UPDATE Ref_Transfert_PP SET ORDRE=9 WHERE UPPER(LIBELLE)='Autre Fch';
UPDATE Ref_Transfert_PP SET ORDRE=10 WHERE UPPER(LIBELLE)='MOI';
UPDATE Ref_Transfert_PP SET ORDRE=11 WHERE UPPER(LIBELLE)='Location';
UPDATE Ref_Transfert_PP SET ORDRE=12 WHERE UPPER(LIBELLE)='Achat';
UPDATE Ref_Transfert_PP SET ORDRE=13 WHERE UPPER(LIBELLE)='Conso';
update Ref_Type_Lot set nom='Autres' where nom='Autre';